# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "huge-tg-demo-bucket"
    dynamodb_table = "tg-state-lock"
    encrypt        = true
    key            = "env3/terraform.tfstate"
    region         = "us-east-1"
  }
}
